### ISSUE TITLE
Cannot find uploaded file

### ISSUE THREAD

**Issue by tno2007** [domharrington/fileupload#14]
I have a simple application:

```
var express = require('express');
var fileupload = require('fileupload').createFileUpload("/uploadDir").middleware;
var app = express();

var SERVER_PORT = 3000;

app.get('/', function(req, res) {
    res.end("upload service running!");
});

app.post('/upload', fileupload, function(req, res) {
    // files are now in the req.body object along with other form fields
    // files also get moved to the uploadDir specified
    console.log("upload done!");
    res.end("upload done!");

});

var server = app.listen(SERVER_PORT, function() {
    console.log("Listening on port " + server.address().port);
});
```

and a simple upload html page:

```
<!DOCTYPE html>
<html>
<body>

<form action="http://localhost:3000/upload" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload">
    <input type="submit" value="Upload file" name="submit">
</form>

</body>
</html>
```

When I upload a file, the uploadDir directory is empty. How do I keep the file that I have uploaded? Am I missing some code?

Thanks

**Comment by domharrington** [comment]
Hi,

I've actually deprecated this module: https://github.com/domharrington/fileupload#deprecation-if-you-need-a-file-upload-middleware-i-would-recommend-using-multer-or-busboy. I've forgotten to publish to NPM with this notice so maybe you missed it.

You should use [multer](https://www.npmjs.com/package/multer) or [busboy](https://www.npmjs.com/package/busboy) instead of this. The usage examples for multer look very similar to this module, but probably work a lot better https://www.npmjs.com/package/multer#usage.

Thanks.
